#!/usr/bin/env bash
#Configuring new ubuntu machine by installing
#Nginx listening on port 80
#Serves a page that would return a Hello World string

echo -e "ngix installation\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nconfiguring\n"

# starts mgix
sudo service nginx start

#permissions of nginx on firewall
sudo ufw allow 'Nginx HTTP'

#ownership settings for server
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#Backing up defualtd index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

#Create new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

#Setting up /
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-fhuhuihwe3 permanent;' /etc/nginx/sites-available/default

# Setting up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
