#!/usr/bin/env bash
# Script that configures HAproxy on server.

sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen load-balance
        bind :80
        bind :8080
        mode http
        balance roundrobin
        option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
        option forwardfor
        server 97653-web-01 54.144.136.154 check port 80
        server 97653-web-02 100.27.3.245 check port 80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
