#!/usr/bin/env bash
#script that loops from 1 to 10
counti=0

while [ $counti -lt 10 ]
do
  if [ $counti -eq 3 ]
  then
    echo "bad luck"
  elif [ $counti -eq 7 ]
  then
    echo "good luck"
  else
    echo "Holberton School"
  fi
  (( counti++ ))
done

